### ISSUE TITLE
Convert .styl to .less files

### ISSUE THREAD

**Issue by jaetea** [atoha/dbootstrap#72]
Considering both Dojo and Bootstrap use LESS files by default could we convert the .styl files to .less files for easier integration?

**Comment by martinpengellyphillips** [comment]
I started out using LESS and became frustrated with it for various reasons. After a bit of research I moved to Stylus and have been happy with it since, so no plans to convert back. From memory, various members of the Dojo community are pushing to adopt Stylus for Dojo 2.0 as well.

What do you mean by easier integration?

**Comment by dylans** [comment]
Agreed, the plan is to move away from LESS to Stylus for several reasons . There are various reasons, but primarily Stylus doesn't have the same unsolved bugs we've experienced with LESS, and in general, the Stylus code base is far more pleasant to use.

Stylus has a more flexible mixin structure, supporting variable arguments. You can easily define variables only if not already defined (e.g. to institute defaults but avoid overriding custom values defined earlier). This, and some pretty major issues with relative paths for image files led us to Stylus.

https://github.com/kfranqueiro/dijit-claro-stylus is a straight conversion from Dijit's LESS to Stylus.

**Comment by jaetea** [comment]
Thanks Dylan. This is really good to know. Will work with .styl files from now on. This can be closed.
